### ISSUE TITLE
MULTI_CHOICE type in preset / profile rendered as simple text input in PoI form

### ISSUE THREAD

**Issue by answerquest** [jawg/osm-contributor#175]
**Description:**
`MULTI_CHOICE` type in preset / profile rendered as simple text input in PoI form.

**Steps to reproduce:**

1. On the phone, start the app, open Menu > Load Profile
1. Choose "toilets preset" at bottom.
1. Back on the app screen, zoom to a place.
1. Find an existing toilet and open it to "Edit poi", or create a new "Public toilets" poi and place it and press tickmark on top right.
1. Form screen: Second question : "Toilets:position". Tap that.
1. There is just a simple text input there.
1. But in the [preset code on h2geo-presets](https://github.com/jawg/h2geo-presets/blob/master/presets/toilets.yml#L53) it's supposed to be a multiple choice question.
1. User ought to have some way of seeing the available options, but there isn't any. User has to type in fresh text. No auto-suggest either.
1. This renders the `MULTI_CHOICE` type in the preset as equal to a simple text input. 

**Expected behavior:**
Multiple choice options with checkboxes

**Actual behavior:**
simple text input, no clues about the options available

**Relevant code snippet:**
Preset for toilets: https://github.com/jawg/h2geo-presets/blob/master/presets/toilets.yml#L53
```
          - key: toilets:position
            type: MULTI_CHOICE
            description:
              default: Position of usage
              fr: La position d'utilisation
              en: Position of usage
            values:
              - seated:
                  default: seated
                  fr: Assis
                  en: Seated
              - squat:
                  default: squat
                  fr: Accroupi
                  en: Squat
              - urinal:
                  default: urinal
                  fr: Debout (urinoir)
                  en: Urinal
            required: false
```

**Environment:**
- Device: Alcatel_4060A (cross-checked other multiple-choice inputs in device's default web browser, works there.)
- Android version: 5.1.1

**Version:**
v3.0.23
